
#ifndef JSTD_CONFIG_DEFAULT_CONFIG_H
#define JSTD_CONFIG_DEFAULT_CONFIG_H

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#if !defined(JIMIC_USE_DEFAULT_CONFIG) || (JIMIC_USE_DEFAULT_CONFIG == 0)

#define JSTD_USE_DEFAULT_CONFIG     1

#endif // JSTD_USE_DEFAULT_CONFIG

#endif // JSTD_CONFIG_DEFAULT_CONFIG_H
